# author: mnoxx @ proton me
# date: Saturday, 24 September 2022 2:24:20 AM
# version: v1.1
# env: powershell(5.x), pwsh(7.x)
stages:
  - Test-PSM # dependencies
  - Build-Module
  - Build-Nuget-Package
  - Deploy-Nuget-Package-gitlab-SH
  - Sync-Nuget-gitlab-Package-To-PSGallary
  - Sync-NextCloud-PSM-Module
  - Sync-GoogleDrive-PSM-Module
build-job:
  stage: build
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  artifacts:
    paths:
    - compiled/folder/from/root
    expire_in: 20 minutes

test-pscore-job:
  stage: test_pscore
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "build" && $CI_BUILD_STATUS == "success"'

test-ps-job:
  stage: test_ps
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'
    
deploy-nugetgitlab-job:
  stage: deploy_nugetgitlab
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'

manual-deploy-psgallary-job:
  stage: manual_deploy_psgallary
  when: manual
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploy_nugetgitlab" && $CI_BUILD_STATUS == "success"'
# Release a Package
package:
  script: Compress-Archive -Path .\Build -DestinationPath Build.gz
  artifacts:
    paths:
    - Build.gz