# author: mnoxx @ proton me
# date: Saturday, 24 September 2022 2:24:20 AM
# version: v1.1
# env: powershell(5.x), pwsh(7.x)
stages:
  - build # dependencies
  - test_pssa # analyze script
  - test_pester # run mock test
  - test_pscore # test PowerShell Core
  - test_ps # test none-powershell Core
  - deploy_nugetgitlab # deploy to NuGet and GitLab
  - manual_deploy_psgallary # manual deploy to PSGallery
  - manual_deplay_choc # chocalte gallary
  # - sync_gitlab_to_psgal_to_choc

build-job:
  stage: build
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"

test-pscore-job:
  stage: test_pscore
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "build" && $CI_BUILD_STATUS == "success"'

test-ps-job:
  stage: test_ps
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'
    
deploy-nugetgitlab-job:
  stage: deploy_nugetgitlab
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "test_pscore" && $CI_BUILD_STATUS == "success"'

manual-deploy-psgallary-job:
  stage: manual_deploy_psgallary
  when: manual
  script:
    - pwsh.exe
    - write-host -f green "template ci/cd config successful"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_BUILD_STAGE == "deploy_nugetgitlab" && $CI_BUILD_STATUS == "success"'